//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arena.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arena.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Areas on Field Report.
        /// </summary>
        public static string AddAreasHelpTitle {
            get {
                return ResourceManager.GetString("AddAreasHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AreaLabel {
            get {
                return ResourceManager.GetString("AreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Photos.
        /// </summary>
        public static string AreaPhotosPageTitle {
            get {
                return ResourceManager.GetString("AreaPhotosPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you at the loss site?.
        /// </summary>
        public static string AreYouAtTheLossSite {
            get {
                return ResourceManager.GetString("AreYouAtTheLossSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL.
        /// </summary>
        public static string CallButton {
            get {
                return ResourceManager.GetString("CallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Permissions not enabled.
        /// </summary>
        public static string CameraPermissionDeniedHeader {
            get {
                return ResourceManager.GetString("CameraPermissionDeniedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera permissions are required to take a photo. Would you like to enable camera permissions?.
        /// </summary>
        public static string CameraPermissionDeniedMessage {
            get {
                return ResourceManager.GetString("CameraPermissionDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string CaptionLabel {
            get {
                return ResourceManager.GetString("CaptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLAIMANT.
        /// </summary>
        public static string ClaimantButton {
            get {
                return ResourceManager.GetString("ClaimantButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant email not found.
        /// </summary>
        public static string ClaimantEmailNotFound {
            get {
                return ResourceManager.GetString("ClaimantEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant Info.
        /// </summary>
        public static string ClaimantInfo {
            get {
                return ResourceManager.GetString("ClaimantInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant Info:.
        /// </summary>
        public static string ClaimantInfoTitle {
            get {
                return ResourceManager.GetString("ClaimantInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant Name:.
        /// </summary>
        public static string ClaimantNameTitle {
            get {
                return ResourceManager.GetString("ClaimantNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant phone number not found.
        /// </summary>
        public static string ClaimantPhoneNotFound {
            get {
                return ResourceManager.GetString("ClaimantPhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new claim with the number {0}..
        /// </summary>
        public static string ClaimCreatedNotificationFormat {
            get {
                return ResourceManager.GetString("ClaimCreatedNotificationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Claim.
        /// </summary>
        public static string ClaimCreateTitle {
            get {
                return ResourceManager.GetString("ClaimCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your claim with the number {0} has been removed/reassigned..
        /// </summary>
        public static string ClaimDeletedNotificationFormat {
            get {
                return ResourceManager.GetString("ClaimDeletedNotificationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Removed.
        /// </summary>
        public static string ClaimDeleteTile {
            get {
                return ResourceManager.GetString("ClaimDeleteTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Details.
        /// </summary>
        public static string ClaimDetailPageTitle {
            get {
                return ResourceManager.GetString("ClaimDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Gallery.
        /// </summary>
        public static string ClaimGalleryPageTitle {
            get {
                return ResourceManager.GetString("ClaimGalleryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacted.
        /// </summary>
        public static string ClaimProgressContacted {
            get {
                return ResourceManager.GetString("ClaimProgressContacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspected.
        /// </summary>
        public static string ClaimProgressInspected {
            get {
                return ResourceManager.GetString("ClaimProgressInspected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ClaimProgressNew {
            get {
                return ResourceManager.GetString("ClaimProgressNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string ClaimProgressSubmitted {
            get {
                return ResourceManager.GetString("ClaimProgressSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Received.
        /// </summary>
        public static string ClaimReceivedTitle {
            get {
                return ResourceManager.GetString("ClaimReceivedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a claim number.
        /// </summary>
        public static string ClaimSearchBody {
            get {
                return ResourceManager.GetString("ClaimSearchBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A claim with number {0} was not found.
        /// </summary>
        public static string ClaimSearchNotFoundFormat {
            get {
                return ResourceManager.GetString("ClaimSearchNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Search.
        /// </summary>
        public static string ClaimSearchTitle {
            get {
                return ResourceManager.GetString("ClaimSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Time Tracker.
        /// </summary>
        public static string ClaimTimeTracker {
            get {
                return ResourceManager.GetString("ClaimTimeTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Time Tracker.
        /// </summary>
        public static string ClaimTrackingsPageTitle {
            get {
                return ResourceManager.GetString("ClaimTrackingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your claim with the number {0} has been updated..
        /// </summary>
        public static string ClaimUpdatedNotificationFormat {
            get {
                return ResourceManager.GetString("ClaimUpdatedNotificationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Update.
        /// </summary>
        public static string ClaimUpdateTitle {
            get {
                return ResourceManager.GetString("ClaimUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on a different pin to compare..
        /// </summary>
        public static string CompareClaimsLabel {
            get {
                return ResourceManager.GetString("CompareClaimsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE SECTION.
        /// </summary>
        public static string CompleteButtonTitle {
            get {
                return ResourceManager.GetString("CompleteButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CompleteText {
            get {
                return ResourceManager.GetString("CompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Contact Time.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacted.
        /// </summary>
        public static string ContactedClaimLegendLabel {
            get {
                return ResourceManager.GetString("ContactedClaimLegendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        public static string ContinueButtonTitle {
            get {
                return ResourceManager.GetString("ContinueButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage Type:.
        /// </summary>
        public static string CoverageTypeTitle {
            get {
                return ResourceManager.GetString("CoverageTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string DateTimePageTitle {
            get {
                return ResourceManager.GetString("DateTimePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string DateTimeTitle {
            get {
                return ResourceManager.GetString("DateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible.
        /// </summary>
        public static string DeductibleTitle {
            get {
                return ResourceManager.GetString("DeductibleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting picture.
        /// </summary>
        public static string DeletingPicture {
            get {
                return ResourceManager.GetString("DeletingPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email isn&apos;t valid.
        /// </summary>
        public static string DialogEmailIsntValidBody {
            get {
                return ResourceManager.GetString("DialogEmailIsntValidBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature is not supported by this device..
        /// </summary>
        public static string DialogFeatureIsNotSupportedBody {
            get {
                return ResourceManager.GetString("DialogFeatureIsNotSupportedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured email not found.
        /// </summary>
        public static string DialogInsuredEmailNotFoundBody {
            get {
                return ResourceManager.GetString("DialogInsuredEmailNotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured phone number not found.
        /// </summary>
        public static string DialogInsuredPhoneNumberNotFoundBody {
            get {
                return ResourceManager.GetString("DialogInsuredPhoneNumberNotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurer email not found.
        /// </summary>
        public static string DialogInsurerEmailNotFoundBody {
            get {
                return ResourceManager.GetString("DialogInsurerEmailNotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurer phone number not found.
        /// </summary>
        public static string DialogInsurerPhoneNumberNotFoundBody {
            get {
                return ResourceManager.GetString("DialogInsurerPhoneNumberNotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        public static string DialogNotNow {
            get {
                return ResourceManager.GetString("DialogNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number isn&apos;t valid.
        /// </summary>
        public static string DialogPhoneNumberIsntValidBody {
            get {
                return ResourceManager.GetString("DialogPhoneNumberIsntValidBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you reach the claimant?.
        /// </summary>
        public static string DidYouReachTheClaimant {
            get {
                return ResourceManager.GetString("DidYouReachTheClaimant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you reach the insured?.
        /// </summary>
        public static string DidYouReachTheInsured {
            get {
                return ResourceManager.GetString("DidYouReachTheInsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string DurationTitle {
            get {
                return ResourceManager.GetString("DurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string EffectiveDateTitle {
            get {
                return ResourceManager.GetString("EffectiveDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EmailButton {
            get {
                return ResourceManager.GetString("EmailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailTitle {
            get {
                return ResourceManager.GetString("EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDateTitle {
            get {
                return ResourceManager.GetString("ExpirationDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add captions to all the photos in your report and try to submit your field report again..
        /// </summary>
        public static string FieldReportDialogMissingCaptionBody {
            get {
                return ResourceManager.GetString("FieldReportDialogMissingCaptionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Later.
        /// </summary>
        public static string FieldReportDialogMissingCaptionNegativeButton {
            get {
                return ResourceManager.GetString("FieldReportDialogMissingCaptionNegativeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Now.
        /// </summary>
        public static string FieldReportDialogMissingCaptionPositiveButton {
            get {
                return ResourceManager.GetString("FieldReportDialogMissingCaptionPositiveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report photos need captions.
        /// </summary>
        public static string FieldReportDialogMissingCaptionTitle {
            get {
                return ResourceManager.GetString("FieldReportDialogMissingCaptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Report.
        /// </summary>
        public static string FieldReportPageTitle {
            get {
                return ResourceManager.GetString("FieldReportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to submit this claim. You cannot undo this action. Are you sure?.
        /// </summary>
        public static string FieldReportSubmitConfirmation {
            get {
                return ResourceManager.GetString("FieldReportSubmitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Report.
        /// </summary>
        public static string FieldReportTitle {
            get {
                return ResourceManager.GetString("FieldReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Contact.
        /// </summary>
        public static string FirstContactPageTitle {
            get {
                return ResourceManager.GetString("FirstContactPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Contact.
        /// </summary>
        public static string FirstContactTitle {
            get {
                return ResourceManager.GetString("FirstContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo-Tag.
        /// </summary>
        public static string GeoTagLabel {
            get {
                return ResourceManager.GetString("GeoTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Details.
        /// </summary>
        public static string ImageDetailsPageTitle {
            get {
                return ResourceManager.GetString("ImageDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgressText {
            get {
                return ResourceManager.GetString("InProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspected.
        /// </summary>
        public static string InspectedClaimLegendLabel {
            get {
                return ResourceManager.GetString("InspectedClaimLegendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Time.
        /// </summary>
        public static string Inspection {
            get {
                return ResourceManager.GetString("Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Inspection Date.
        /// </summary>
        public static string InspectionDateTitle {
            get {
                return ResourceManager.GetString("InspectionDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Details.
        /// </summary>
        public static string InspectionPageTitle {
            get {
                return ResourceManager.GetString("InspectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSURED.
        /// </summary>
        public static string InsuredButton {
            get {
                return ResourceManager.GetString("InsuredButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Info.
        /// </summary>
        public static string InsuredInfo {
            get {
                return ResourceManager.GetString("InsuredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Info:.
        /// </summary>
        public static string InsuredInfoTitle {
            get {
                return ResourceManager.GetString("InsuredInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Name:.
        /// </summary>
        public static string InsuredNameTitle {
            get {
                return ResourceManager.GetString("InsuredNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurer Contact.
        /// </summary>
        public static string InsurerContactTitle {
            get {
                return ResourceManager.GetString("InsurerContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurer Details.
        /// </summary>
        public static string InsurerDetailsPageTitle {
            get {
                return ResourceManager.GetString("InsurerDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurer Details.
        /// </summary>
        public static string InsurerDetailsTitle {
            get {
                return ResourceManager.GetString("InsurerDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurer Name.
        /// </summary>
        public static string InsurerNameTitle {
            get {
                return ResourceManager.GetString("InsurerNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurer Reference.
        /// </summary>
        public static string InsurerReferenceTitle {
            get {
                return ResourceManager.GetString("InsurerReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption Missing.
        /// </summary>
        public static string InvalidPhotoDescription {
            get {
                return ResourceManager.GetString("InvalidPhotoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Status:.
        /// </summary>
        public static string LatestClaimStatus {
            get {
                return ResourceManager.GetString("LatestClaimStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string LimitTitle {
            get {
                return ResourceManager.GetString("LimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Permissions not enabled.
        /// </summary>
        public static string LocationPermissionDeniedHeader {
            get {
                return ResourceManager.GetString("LocationPermissionDeniedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location permissions are required for the Lightning app in order to access your claims. In addition, regulations require that inspection photos contain geolocation data. Would you like to enable location permissions?.
        /// </summary>
        public static string LocationPermissionDeniedMessage {
            get {
                return ResourceManager.GetString("LocationPermissionDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance Your Map View.
        /// </summary>
        public static string LocationPermissionHeader {
            get {
                return ResourceManager.GetString("LocationPermissionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location permissions are required for the Lightning App in order to access to your claims and to take inspection photos. Would you like to enable location permissions?.
        /// </summary>
        public static string LocationPermissionMessage {
            get {
                return ResourceManager.GetString("LocationPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Date.
        /// </summary>
        public static string LossDateTitle {
            get {
                return ResourceManager.GetString("LossDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Offset.
        /// </summary>
        public static string MandatorySelectAddTitle {
            get {
                return ResourceManager.GetString("MandatorySelectAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas haven&apos;t been defined on this report.
        /// </summary>
        public static string MultiSelectAddListHeader {
            get {
                return ResourceManager.GetString("MultiSelectAddListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Area.
        /// </summary>
        public static string MultiSelectAddTitle {
            get {
                return ResourceManager.GetString("MultiSelectAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Room Name.
        /// </summary>
        public static string MultiSelectEditAletPlaceholder {
            get {
                return ResourceManager.GetString("MultiSelectEditAletPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Area.
        /// </summary>
        public static string MultiSelectEditAletTitle {
            get {
                return ResourceManager.GetString("MultiSelectEditAletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do with {0}?.
        /// </summary>
        public static string MultiSelectLongTapAletMessageFormat {
            get {
                return ResourceManager.GetString("MultiSelectLongTapAletMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select action:.
        /// </summary>
        public static string MultiSelectLongTapAletTitle {
            get {
                return ResourceManager.GetString("MultiSelectLongTapAletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot; from this report?.
        /// </summary>
        public static string MultiSelectRemoveAletTitleFormat {
            get {
                return ResourceManager.GetString("MultiSelectRemoveAletTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameTitle {
            get {
                return ResourceManager.GetString("NameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECTIONS TO CLAIM LOCATION.
        /// </summary>
        public static string NavigateToClaimButton {
            get {
                return ResourceManager.GetString("NavigateToClaimButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Time.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewClaimLegendLabel {
            get {
                return ResourceManager.GetString("NewClaimLegendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New claims are available!.
        /// </summary>
        public static string NewClaimsLabel {
            get {
                return ResourceManager.GetString("NewClaimsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no photographs
        ///associated with this claim..
        /// </summary>
        public static string NoClaimPhotosTitle {
            get {
                return ResourceManager.GetString("NoClaimPhotosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Claims Currently Assigned.
        /// </summary>
        public static string NoClaimsLabel {
            get {
                return ResourceManager.GetString("NoClaimsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Time Tracked.
        /// </summary>
        public static string OverallTimeTracked {
            get {
                return ResourceManager.GetString("OverallTimeTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Services permission is required to use Arena. Please enable these permissions on your phone settings..
        /// </summary>
        public static string PermissionRequiredLabel {
            get {
                return ResourceManager.GetString("PermissionRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneTitle {
            get {
                return ResourceManager.GetString("PhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Capture.
        /// </summary>
        public static string PhotoCapturePageTitle {
            get {
                return ResourceManager.GetString("PhotoCapturePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this picture?.
        /// </summary>
        public static string PictureDeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("PictureDeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Details.
        /// </summary>
        public static string PolicyDetailsPageTitle {
            get {
                return ResourceManager.GetString("PolicyDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Details.
        /// </summary>
        public static string PolicyDetailsTitle {
            get {
                return ResourceManager.GetString("PolicyDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Number:.
        /// </summary>
        public static string PolicyNumberTitle {
            get {
                return ResourceManager.GetString("PolicyNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your report could not be submitted to CTABS. Please check your connectivity and try again..
        /// </summary>
        public static string ReportSubmitErrorMessage {
            get {
                return ResourceManager.GetString("ReportSubmitErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your report has been submitted to CTABS..
        /// </summary>
        public static string ReportSubmitThankYouMessage {
            get {
                return ResourceManager.GetString("ReportSubmitThankYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on the map to return to map.
        /// </summary>
        public static string ReturnToTheMapHintDroid {
            get {
                return ResourceManager.GetString("ReturnToTheMapHintDroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe down on the claim summary to return to map.
        /// </summary>
        public static string ReturnToTheMapHintiOS {
            get {
                return ResourceManager.GetString("ReturnToTheMapHintiOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Claim Details.
        /// </summary>
        public static string SeeMoreButton {
            get {
                return ResourceManager.GetString("SeeMoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select action:.
        /// </summary>
        public static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take me to Settings.
        /// </summary>
        public static string SettingsConfirm {
            get {
                return ResourceManager.GetString("SettingsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Inspection Timer.
        /// </summary>
        public static string StartInspectionTimer {
            get {
                return ResourceManager.GetString("StartInspectionTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Permissions not enabled.
        /// </summary>
        public static string StoragePermissionDeniedHeader {
            get {
                return ResourceManager.GetString("StoragePermissionDeniedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage permissions are required to take a photo. Would you like to enable storage permissions?.
        /// </summary>
        public static string StoragePermissionDeniedMessage {
            get {
                return ResourceManager.GetString("StoragePermissionDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once your times are submitted the information will be sent to CTABS and the times themselves can&apos;t be modified on the Lightning app..
        /// </summary>
        public static string SubmitAllTrackingMessage {
            get {
                return ResourceManager.GetString("SubmitAllTrackingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to submit times?.
        /// </summary>
        public static string SubmitAllTrackingTitle {
            get {
                return ResourceManager.GetString("SubmitAllTrackingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Report.
        /// </summary>
        public static string SubmitReport {
            get {
                return ResourceManager.GetString("SubmitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string SubmittedClaimLegendLabel {
            get {
                return ResourceManager.GetString("SubmittedClaimLegendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting.
        /// </summary>
        public static string Submitting {
            get {
                return ResourceManager.GetString("Submitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once your time is submitted the information will be sent to CTABS and the time itself can&apos;t be modified on the Lightning app..
        /// </summary>
        public static string SubmitTrackingMessage {
            get {
                return ResourceManager.GetString("SubmitTrackingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to submit time?.
        /// </summary>
        public static string SubmitTrackingTitle {
            get {
                return ResourceManager.GetString("SubmitTrackingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on a pin to select a claim in your area..
        /// </summary>
        public static string TapOnAPinToSelect {
            get {
                return ResourceManager.GetString("TapOnAPinToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the fields on all your tracked times and try again..
        /// </summary>
        public static string TrackingIncompleteMessage {
            get {
                return ResourceManager.GetString("TrackingIncompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked times are incomplete.
        /// </summary>
        public static string TrackingIncompleteTitle {
            get {
                return ResourceManager.GetString("TrackingIncompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string TrackingNoteTitle {
            get {
                return ResourceManager.GetString("TrackingNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll do this later.
        /// </summary>
        public static string TrackingNotSubmittedCancel {
            get {
                return ResourceManager.GetString("TrackingNotSubmittedCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete and submit your tracked times and then try to submit your field report again..
        /// </summary>
        public static string TrackingNotSubmittedMessage {
            get {
                return ResourceManager.GetString("TrackingNotSubmittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Timers.
        /// </summary>
        public static string TrackingNotSubmittedReview {
            get {
                return ResourceManager.GetString("TrackingNotSubmittedReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked time not submitted.
        /// </summary>
        public static string TrackingNotSubmittedTille {
            get {
                return ResourceManager.GetString("TrackingNotSubmittedTille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a detailed summary:.
        /// </summary>
        public static string TrackingPageHintTitle {
            get {
                return ResourceManager.GetString("TrackingPageHintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive time from site.
        /// </summary>
        public static string TravelFromPlaceholder {
            get {
                return ResourceManager.GetString("TravelFromPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Location.
        /// </summary>
        public static string TravelFromTitle {
            get {
                return ResourceManager.GetString("TravelFromTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Time.
        /// </summary>
        public static string TravelPageTitle {
            get {
                return ResourceManager.GetString("TravelPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive time to site.
        /// </summary>
        public static string TravelToPlaceholder {
            get {
                return ResourceManager.GetString("TravelToPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Location.
        /// </summary>
        public static string TravelToTitle {
            get {
                return ResourceManager.GetString("TravelToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Report.
        /// </summary>
        public static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do with {0}?.
        /// </summary>
        public static string WhatDoYouWantToDoWith {
            get {
                return ResourceManager.GetString("WhatDoYouWantToDoWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
